package com.daiphat.coreapi.domain.model.lotteries;

import com.daiphat.coreapi.domain.model.enums.lottery.SupplierSettlementAdjustmentGroupType;
import com.daiphat.coreapi.domain.model.enums.lottery.SupplierSettlementAdjustmentReasonCode;
import com.daiphat.coreapi.shared.util.ImportCostCalculator;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SupplierSettlementAdjustmentModel {

    private Long id;
    private Long supplierSettlementId;
    private Long lotteryTicketSerialId;
    private SupplierSettlementAdjustmentGroupType groupType;
    private SupplierSettlementAdjustmentReasonCode reasonCode;
    @Builder.Default
    private BigDecimal amount = BigDecimal.ZERO;
    private String customName;
    private String note;
    @Builder.Default
    private boolean autoGenerated = false;
    private UUID resolvedBy;
    private LocalDateTime createdAt;

    public void applyAmount(BigDecimal amount) {
        this.amount = ImportCostCalculator.scaleMoney(amount);
    }
}
