package com.daiphat.coreapi.application.dto.response.lotteries;

import com.daiphat.coreapi.domain.model.enums.lottery.SupplierSettlementAdjustmentGroupType;
import com.daiphat.coreapi.domain.model.enums.lottery.SupplierSettlementAdjustmentReasonCode;
import lombok.Builder;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Builder
public record SupplierSettlementAdjustmentResponse(
        Long id,
        Long supplierSettlementId,
        Long lotteryTicketSerialId,
        SupplierSettlementAdjustmentGroupType groupType,
        SupplierSettlementAdjustmentReasonCode reasonCode,
        String reasonLabel,
        BigDecimal amount,
        String customName,
        Boolean autoGenerated,
        String note,
        UUID resolvedBy,
        LocalDateTime createdAt
) {
}
