package com.daiphat.coreapi.application.dto.response.streetagent;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

public record VendorAllocationBatchResponse(
        Long id,
        String batchCode,
        Long streetAgentProfileId,
        LocalDate businessDate,
        String status,
        LocalDateTime reservationExpiresAt,
        Integer requestedQuantity,
        Integer reserveCountSnapshot,
        BigDecimal reservePercentSnapshot,
        int allocatedQuantity,
        int remainingDailyCap,
        BigDecimal faceValueSnapshot,
        BigDecimal vendorUnitPriceSnapshot,
        BigDecimal commissionRateSnapshot,
        BigDecimal depositRateSnapshot,
        String latePolicySnapshot,
        LocalTime returnCutoffSnapshot,
        LocalTime supplierReturnCutoffSnapshot,
        Integer returnBufferMinutesSnapshot,
        LocalDateTime effectiveHandoverDeadlineAt,
        BigDecimal depositRequiredAmount,
        BigDecimal depositReceivedAmount,
        BigDecimal depositBalanceBefore,
        BigDecimal depositBalanceAfter,
        LocalDateTime depositReceivedAt,
        LocalDateTime settledAt,
        int returnedQuantity,
        int soldQuantity,
        BigDecimal grossCashRemitted,
        BigDecimal commissionPayable,
        BigDecimal agencyNetSalesAmount,
        BigDecimal depositRefundAmount,
        BigDecimal depositForfeitedAmount,
        BigDecimal depositAppliedAmount,
        BigDecimal depositExcessRefundAmount,
        BigDecimal forcedPurchaseAmount,
        BigDecimal additionalAmountDue,
        Long agentSettlementId,
        Long dailySalesReportId,
        Long returnBatchId,
        VendorAllocationReturnWorkflowResponse returnWorkflow,
        List<VendorAllocationBatchDetailResponse> details,
        List<VendorAllocationSerialResponse> serials
) {
}
