-- =============================================================================
-- Manual test seeder: MEMBER phu123 + 50 winning tickets across multiple orders
-- =============================================================================
-- Prerequisites (already present from Flyway / Java station seed):
--   * roles.ROLE_MEMBER
--   * ≥3 active lottery_stations
--   * prize_structures for MIEN_NAM (DB, G1–G8, DB_PHU, KK)
--
-- Creates / upserts:
--   * users.username = phu123 / password Phu123A (BCrypt) / ROLE_MEMBER
--   * 50 lottery_tickets + serials (prefix PHU123W-)
--   * COMPLETED lottery_results matching those wins
--   * 12 ONLINE COMPLETED orders ORD-PHU123-WIN-001..012 owned by phu123
--   * 30 PROXY_HOLDING lines → online-claim eligible (G3–G8, KK ≤ 10M)
--   * 20 HANDED_OVER lines → in-person only (DB, G1, G2, DB_PHU)
--
-- Idempotent: re-running deletes prior rows tagged PHU123_WIN50_SEED / prefixes.
-- Apply:  psql -U <user> -d <db> -f scripts/seed_phu123_win50_online_claim.sql
-- Regenerated by: python scripts/generate_seed_phu123_win50.py
-- =============================================================================

BEGIN;

-- ---------- cleanup previous run ----------
DELETE FROM prize_payout_requests
 WHERE serial_id IN (
     SELECT id FROM lottery_ticket_serials WHERE serial_number LIKE 'PHU123W-%'
 )
    OR order_id IN (SELECT id FROM orders WHERE order_code LIKE 'ORD-PHU123-WIN-%');

DELETE FROM order_details
 WHERE order_id IN (SELECT id FROM orders WHERE order_code LIKE 'ORD-PHU123-WIN-%');
DELETE FROM transactions
 WHERE order_id IN (SELECT id FROM orders WHERE order_code LIKE 'ORD-PHU123-WIN-%')
    OR payment_ref LIKE 'PAYOS-PHU123-WIN-%';
DELETE FROM orders WHERE order_code LIKE 'ORD-PHU123-WIN-%';

DELETE FROM lottery_result_details
 WHERE lottery_result_id IN (
     SELECT id FROM lottery_results
      WHERE created_by = 'PHU123_WIN50_SEED'
         OR last_modified_by = 'PHU123_WIN50_SEED'
 );
DELETE FROM lottery_results
 WHERE created_by = 'PHU123_WIN50_SEED'
    OR last_modified_by = 'PHU123_WIN50_SEED';

DELETE FROM lottery_ticket_serials WHERE serial_number LIKE 'PHU123W-%';
DELETE FROM lottery_tickets WHERE batch_code = 'PN-PHU123-WIN';

DELETE FROM user_bank_accounts
 WHERE user_id IN (SELECT id FROM users WHERE username = 'phu123');

-- ---------- member user phu123 ----------
INSERT INTO users (
    id, role_id, username, email, phone, first_name, last_name,
    status, is_email_verified, agreed_to_terms, has_password, password,
    created_at, updated_at, created_by, last_modified_by
)
SELECT
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890'::uuid,
    r.id,
    'phu123',
    'phu123@daiphat.test',
    '0909123123',
    'Phu',
    'Nguyen',
    'ACTIVE',
    TRUE,
    TRUE,
    TRUE,
    '$2a$10$3GYnYpgK8o0bz2RIFYgl9OPSCiStpUdNfRIRzqdltJcgN3aILE7Jy',
    NOW(),
    NOW(),
    'PHU123_WIN50_SEED',
    'PHU123_WIN50_SEED'
FROM roles r
WHERE r.code = 'ROLE_MEMBER' AND r.deleted_at IS NULL
ON CONFLICT (username) DO UPDATE SET
    role_id = EXCLUDED.role_id,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    status = 'ACTIVE',
    is_email_verified = TRUE,
    has_password = TRUE,
    password = EXCLUDED.password,
    deleted_at = NULL,
    updated_at = NOW(),
    last_modified_by = 'PHU123_WIN50_SEED';

-- If username conflict path updated a different id, align to fixed UUID when free.
-- (No-op when phu123 already owns MEMBER_UUID.)

INSERT INTO user_bank_accounts (
    user_id, bank_name, bank_bin, bank_account_no, bank_account_name,
    is_default, created_at, updated_at, created_by, last_modified_by
)
SELECT
    u.id,
    'Vietcombank',
    '970436',
    '0123456789',
    'NGUYEN PHU',
    TRUE,
    NOW(),
    NOW(),
    'PHU123_WIN50_SEED',
    'PHU123_WIN50_SEED'
FROM users u
WHERE u.username = 'phu123' AND u.deleted_at IS NULL
ON CONFLICT (user_id, bank_bin, bank_account_no) DO UPDATE SET
    is_default = TRUE,
    bank_account_name = EXCLUDED.bank_account_name,
    updated_at = NOW();

-- Staging table for winners (station_slot 0..2 maps to 3 active stations by id ASC)
CREATE TEMP TABLE tmp_phu123_winners (
    idx            INT PRIMARY KEY,
    station_slot   INT NOT NULL,
    draw_offset    INT NOT NULL,
    numbers        VARCHAR(20) NOT NULL,
    prize          VARCHAR(20) NOT NULL,
    online_claim   BOOLEAN NOT NULL,
    serial_number  VARCHAR(100) NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_phu123_winners (idx, station_slot, draw_offset, numbers, prize, online_claim, serial_number) VALUES
    (1, 0, 8, '582917', 'DB', FALSE, 'PHU123W-001-582917'),
    (2, 1, 9, '316842', 'DB', FALSE, 'PHU123W-002-316842'),
    (3, 2, 10, '749063', 'DB', FALSE, 'PHU123W-003-749063'),
    (4, 0, 11, '582917', 'DB', FALSE, 'PHU123W-004-582917'),
    (5, 1, 12, '316842', 'DB', FALSE, 'PHU123W-005-316842'),
    (6, 2, 8, '385714', 'G1', FALSE, 'PHU123W-006-385714'),
    (7, 0, 9, '739204', 'G1', FALSE, 'PHU123W-007-739204'),
    (8, 1, 10, '107391', 'G1', FALSE, 'PHU123W-008-107391'),
    (9, 2, 11, '585714', 'G1', FALSE, 'PHU123W-009-585714'),
    (10, 0, 12, '939204', 'G1', FALSE, 'PHU123W-010-939204'),
    (11, 1, 8, '824156', 'G2', FALSE, 'PHU123W-011-824156'),
    (12, 2, 9, '230195', 'G2', FALSE, 'PHU123W-012-230195'),
    (13, 0, 10, '646385', 'G2', FALSE, 'PHU123W-013-646385'),
    (14, 1, 11, '024156', 'G2', FALSE, 'PHU123W-014-024156'),
    (15, 2, 12, '430195', 'G2', FALSE, 'PHU123W-015-430195'),
    (16, 0, 8, '301572', 'G3', TRUE, 'PHU123W-016-301572'),
    (17, 1, 9, '793047', 'G3', TRUE, 'PHU123W-017-793047'),
    (18, 2, 10, '117826', 'G3', TRUE, 'PHU123W-018-117826'),
    (19, 0, 11, '501572', 'G3', TRUE, 'PHU123W-019-501572'),
    (20, 1, 12, '993047', 'G3', TRUE, 'PHU123W-020-993047'),
    (21, 2, 8, '858301', 'G4', TRUE, 'PHU123W-021-858301'),
    (22, 0, 9, '264830', 'G4', TRUE, 'PHU123W-022-264830'),
    (23, 1, 10, '652978', 'G4', TRUE, 'PHU123W-023-652978'),
    (24, 2, 11, '058301', 'G4', TRUE, 'PHU123W-024-058301'),
    (25, 0, 12, '464830', 'G4', TRUE, 'PHU123W-025-464830'),
    (26, 1, 8, '334061', 'G5', TRUE, 'PHU123W-026-334061'),
    (27, 2, 9, '972740', 'G5', TRUE, 'PHU123W-027-972740'),
    (28, 0, 10, '611583', 'G5', TRUE, 'PHU123W-028-611583'),
    (29, 1, 11, '254061', 'G5', TRUE, 'PHU123W-029-254061'),
    (30, 2, 12, '892740', 'G5', TRUE, 'PHU123W-030-892740'),
    (31, 0, 8, '186729', 'G6', TRUE, 'PHU123W-031-186729'),
    (32, 1, 9, '829382', 'G6', TRUE, 'PHU123W-032-829382'),
    (33, 2, 10, '468516', 'G6', TRUE, 'PHU123W-033-468516'),
    (34, 0, 11, '106729', 'G6', TRUE, 'PHU123W-034-106729'),
    (35, 1, 12, '606567', 'G7', TRUE, 'PHU123W-035-606567'),
    (36, 2, 8, '770392', 'G7', TRUE, 'PHU123W-036-770392'),
    (37, 0, 9, '934418', 'G7', TRUE, 'PHU123W-037-934418'),
    (38, 1, 10, '098567', 'G7', TRUE, 'PHU123W-038-098567'),
    (39, 2, 11, '399464', 'G8', TRUE, 'PHU123W-039-399464'),
    (40, 0, 12, '515873', 'G8', TRUE, 'PHU123W-040-515873'),
    (41, 1, 8, '632229', 'G8', TRUE, 'PHU123W-041-632229'),
    (42, 2, 9, '748664', 'G8', TRUE, 'PHU123W-042-748664'),
    (43, 0, 10, '182917', 'DB_PHU', FALSE, 'PHU123W-043-182917'),
    (44, 1, 11, '116842', 'DB_PHU', FALSE, 'PHU123W-044-116842'),
    (45, 2, 12, '049063', 'DB_PHU', FALSE, 'PHU123W-045-049063'),
    (46, 0, 8, '782917', 'DB_PHU', FALSE, 'PHU123W-046-782917'),
    (47, 1, 9, '716842', 'DB_PHU', FALSE, 'PHU123W-047-716842'),
    (48, 2, 10, '759063', 'KK', TRUE, 'PHU123W-048-759063'),
    (49, 0, 11, '582217', 'KK', TRUE, 'PHU123W-049-582217'),
    (50, 1, 12, '316847', 'KK', TRUE, 'PHU123W-050-316847');

CREATE TEMP TABLE tmp_phu123_results (
    station_slot INT NOT NULL,
    draw_offset  INT NOT NULL,
    prize_code   VARCHAR(20) NOT NULL,
    winning_number VARCHAR(20) NOT NULL,
    PRIMARY KEY (station_slot, draw_offset, prize_code)
) ON COMMIT DROP;

INSERT INTO tmp_phu123_results (station_slot, draw_offset, prize_code, winning_number) VALUES
    (0, 8, 'DB', '582917'),
    (0, 8, 'G1', '139204'),
    (0, 8, 'G2', '746385'),
    (0, 8, 'G3', '901572'),
    (0, 8, 'G4', '264830'),
    (0, 8, 'G5', '1583'),
    (0, 8, 'G6', '6729'),
    (0, 8, 'G7', '418'),
    (0, 8, 'G8', '73'),
    (0, 8, 'DB_PHU', '582917'),
    (0, 8, 'KK', '582917'),
    (0, 9, 'DB', '582917'),
    (0, 9, 'G1', '139204'),
    (0, 9, 'G2', '746385'),
    (0, 9, 'G3', '901572'),
    (0, 9, 'G4', '264830'),
    (0, 9, 'G5', '1583'),
    (0, 9, 'G6', '6729'),
    (0, 9, 'G7', '418'),
    (0, 9, 'G8', '73'),
    (0, 9, 'DB_PHU', '582917'),
    (0, 9, 'KK', '582917'),
    (0, 10, 'DB', '582917'),
    (0, 10, 'G1', '139204'),
    (0, 10, 'G2', '746385'),
    (0, 10, 'G3', '901572'),
    (0, 10, 'G4', '264830'),
    (0, 10, 'G5', '1583'),
    (0, 10, 'G6', '6729'),
    (0, 10, 'G7', '418'),
    (0, 10, 'G8', '73'),
    (0, 10, 'DB_PHU', '582917'),
    (0, 10, 'KK', '582917'),
    (0, 11, 'DB', '582917'),
    (0, 11, 'G1', '139204'),
    (0, 11, 'G2', '746385'),
    (0, 11, 'G3', '901572'),
    (0, 11, 'G4', '264830'),
    (0, 11, 'G5', '1583'),
    (0, 11, 'G6', '6729'),
    (0, 11, 'G7', '418'),
    (0, 11, 'G8', '73'),
    (0, 11, 'DB_PHU', '582917'),
    (0, 11, 'KK', '582917'),
    (0, 12, 'DB', '582917'),
    (0, 12, 'G1', '139204'),
    (0, 12, 'G2', '746385'),
    (0, 12, 'G3', '901572'),
    (0, 12, 'G4', '264830'),
    (0, 12, 'G5', '1583'),
    (0, 12, 'G6', '6729'),
    (0, 12, 'G7', '418'),
    (0, 12, 'G8', '73'),
    (0, 12, 'DB_PHU', '582917'),
    (0, 12, 'KK', '582917'),
    (1, 8, 'DB', '316842'),
    (1, 8, 'G1', '507391'),
    (1, 8, 'G2', '824156'),
    (1, 8, 'G3', '693047'),
    (1, 8, 'G4', '152978'),
    (1, 8, 'G5', '4061'),
    (1, 8, 'G6', '9382'),
    (1, 8, 'G7', '567'),
    (1, 8, 'G8', '29'),
    (1, 8, 'DB_PHU', '316842'),
    (1, 8, 'KK', '316842'),
    (1, 9, 'DB', '316842'),
    (1, 9, 'G1', '507391'),
    (1, 9, 'G2', '824156'),
    (1, 9, 'G3', '693047'),
    (1, 9, 'G4', '152978'),
    (1, 9, 'G5', '4061'),
    (1, 9, 'G6', '9382'),
    (1, 9, 'G7', '567'),
    (1, 9, 'G8', '29'),
    (1, 9, 'DB_PHU', '316842'),
    (1, 9, 'KK', '316842'),
    (1, 10, 'DB', '316842'),
    (1, 10, 'G1', '507391'),
    (1, 10, 'G2', '824156'),
    (1, 10, 'G3', '693047'),
    (1, 10, 'G4', '152978'),
    (1, 10, 'G5', '4061'),
    (1, 10, 'G6', '9382'),
    (1, 10, 'G7', '567'),
    (1, 10, 'G8', '29'),
    (1, 10, 'DB_PHU', '316842'),
    (1, 10, 'KK', '316842'),
    (1, 11, 'DB', '316842'),
    (1, 11, 'G1', '507391'),
    (1, 11, 'G2', '824156'),
    (1, 11, 'G3', '693047'),
    (1, 11, 'G4', '152978'),
    (1, 11, 'G5', '4061'),
    (1, 11, 'G6', '9382'),
    (1, 11, 'G7', '567'),
    (1, 11, 'G8', '29'),
    (1, 11, 'DB_PHU', '316842'),
    (1, 11, 'KK', '316842'),
    (1, 12, 'DB', '316842'),
    (1, 12, 'G1', '507391'),
    (1, 12, 'G2', '824156'),
    (1, 12, 'G3', '693047'),
    (1, 12, 'G4', '152978'),
    (1, 12, 'G5', '4061'),
    (1, 12, 'G6', '9382'),
    (1, 12, 'G7', '567'),
    (1, 12, 'G8', '29'),
    (1, 12, 'DB_PHU', '316842'),
    (1, 12, 'KK', '316842'),
    (2, 8, 'DB', '749063'),
    (2, 8, 'G1', '285714'),
    (2, 8, 'G2', '630195'),
    (2, 8, 'G3', '417826'),
    (2, 8, 'G4', '958301'),
    (2, 8, 'G5', '2740'),
    (2, 8, 'G6', '8516'),
    (2, 8, 'G7', '392'),
    (2, 8, 'G8', '64'),
    (2, 8, 'DB_PHU', '749063'),
    (2, 8, 'KK', '749063'),
    (2, 9, 'DB', '749063'),
    (2, 9, 'G1', '285714'),
    (2, 9, 'G2', '630195'),
    (2, 9, 'G3', '417826'),
    (2, 9, 'G4', '958301'),
    (2, 9, 'G5', '2740'),
    (2, 9, 'G6', '8516'),
    (2, 9, 'G7', '392'),
    (2, 9, 'G8', '64'),
    (2, 9, 'DB_PHU', '749063'),
    (2, 9, 'KK', '749063'),
    (2, 10, 'DB', '749063'),
    (2, 10, 'G1', '285714'),
    (2, 10, 'G2', '630195'),
    (2, 10, 'G3', '417826'),
    (2, 10, 'G4', '958301'),
    (2, 10, 'G5', '2740'),
    (2, 10, 'G6', '8516'),
    (2, 10, 'G7', '392'),
    (2, 10, 'G8', '64'),
    (2, 10, 'DB_PHU', '749063'),
    (2, 10, 'KK', '749063'),
    (2, 11, 'DB', '749063'),
    (2, 11, 'G1', '285714'),
    (2, 11, 'G2', '630195'),
    (2, 11, 'G3', '417826'),
    (2, 11, 'G4', '958301'),
    (2, 11, 'G5', '2740'),
    (2, 11, 'G6', '8516'),
    (2, 11, 'G7', '392'),
    (2, 11, 'G8', '64'),
    (2, 11, 'DB_PHU', '749063'),
    (2, 11, 'KK', '749063'),
    (2, 12, 'DB', '749063'),
    (2, 12, 'G1', '285714'),
    (2, 12, 'G2', '630195'),
    (2, 12, 'G3', '417826'),
    (2, 12, 'G4', '958301'),
    (2, 12, 'G5', '2740'),
    (2, 12, 'G6', '8516'),
    (2, 12, 'G7', '392'),
    (2, 12, 'G8', '64'),
    (2, 12, 'DB_PHU', '749063'),
    (2, 12, 'KK', '749063');

DO $$
DECLARE
    v_member      UUID;
    v_importer    UUID;
    v_stations    BIGINT[];
    v_region_id   BIGINT;
    v_station_id  BIGINT;
    v_draw_date   DATE;
    v_ticket_id   BIGINT;
    v_serial_id   BIGINT;
    v_result_id   BIGINT;
    v_ps_id       BIGINT;
    v_order_id    UUID;
    v_paid_at     TIMESTAMP;
    v_pickup_at   TIMESTAMP;
    v_total       NUMERIC(15,0);
    v_slots       INT;
    r_win         RECORD;
    r_res         RECORD;
    r_plan        RECORD;
BEGIN
    SELECT id INTO v_member FROM users WHERE username = 'phu123' AND deleted_at IS NULL;
    IF v_member IS NULL THEN
        RAISE EXCEPTION 'phu123 user missing after upsert';
    END IF;

    -- Prefer staff operator for imported_by / handover; fall back to member.
    SELECT u.id INTO v_importer
    FROM users u
    JOIN roles r ON r.id = u.role_id
    WHERE u.deleted_at IS NULL
      AND r.code IN ('ROLE_STAFF_OPERATOR', 'ROLE_ADMIN')
    ORDER BY CASE r.code
        WHEN 'ROLE_STAFF_OPERATOR' THEN 0
        WHEN 'ROLE_ADMIN' THEN 1
        ELSE 2 END
    LIMIT 1;
    IF v_importer IS NULL THEN
        v_importer := v_member;
    END IF;

    SELECT array_agg(id ORDER BY id) INTO v_stations
    FROM (
        SELECT id
        FROM lottery_stations
        WHERE deleted_at IS NULL AND COALESCE(is_active, TRUE) = TRUE
        ORDER BY id
        LIMIT 3
    ) s;
    IF v_stations IS NULL OR array_length(v_stations, 1) < 3 THEN
        RAISE EXCEPTION 'Need ≥3 active lottery_stations (run SouthernLotteryStationSeed)';
    END IF;

    SELECT id INTO v_region_id FROM lottery_regions WHERE code = 'MIEN_NAM' LIMIT 1;
    IF v_region_id IS NULL THEN
        SELECT region_id INTO v_region_id FROM prize_structures
        WHERE prize_code = 'DB' AND deleted_at IS NULL LIMIT 1;
    END IF;
    IF v_region_id IS NULL THEN
        RAISE EXCEPTION 'prize_structures / MIEN_NAM region missing';
    END IF;

    -- Ensure all required prize codes exist
    IF (SELECT COUNT(*) FROM prize_structures
        WHERE region_id = v_region_id AND deleted_at IS NULL
          AND prize_code IN ('DB','G1','G2','G3','G4','G5','G6','G7','G8','DB_PHU','KK')) < 11 THEN
        RAISE EXCEPTION 'Missing southern prize_structures (need DB,G1-G8,DB_PHU,KK)';
    END IF;

    -- ---- lottery results ----
    FOR r_res IN
        SELECT DISTINCT station_slot, draw_offset FROM tmp_phu123_results
    LOOP
        v_station_id := v_stations[r_res.station_slot + 1];
        v_draw_date := CURRENT_DATE - r_res.draw_offset;

        -- Refuse to clobber a non-seed result for the same station/date.
        IF EXISTS (
            SELECT 1 FROM lottery_results lr
             WHERE lr.station_id = v_station_id
               AND lr.draw_date = v_draw_date
               AND lr.deleted_at IS NULL
               AND COALESCE(lr.created_by, '') NOT IN ('PHU123_WIN50_SEED')
               AND COALESCE(lr.last_modified_by, '') NOT IN ('PHU123_WIN50_SEED')
        ) THEN
            RAISE EXCEPTION
                'lottery_results already exists for station % on % (not owned by PHU123_WIN50_SEED). Clear it or change DRAW_OFFSETS.',
                v_station_id, v_draw_date;
        END IF;

        INSERT INTO lottery_results (
            station_id, draw_date, source, is_official, status, published_at,
            created_at, updated_at, created_by, last_modified_by
        ) VALUES (
            v_station_id, v_draw_date, 'MANUAL', TRUE, 'COMPLETED',
            (v_draw_date + TIME '16:35'),
            NOW(), NOW(), 'PHU123_WIN50_SEED', 'PHU123_WIN50_SEED'
        )
        ON CONFLICT (station_id, draw_date) DO UPDATE SET
            source = 'MANUAL',
            is_official = TRUE,
            status = 'COMPLETED',
            published_at = EXCLUDED.published_at,
            deleted_at = NULL,
            updated_at = NOW(),
            created_by = 'PHU123_WIN50_SEED',
            last_modified_by = 'PHU123_WIN50_SEED'
        RETURNING id INTO v_result_id;

        SELECT id INTO v_result_id FROM lottery_results
        WHERE station_id = v_station_id AND draw_date = v_draw_date;

        DELETE FROM lottery_result_details WHERE lottery_result_id = v_result_id;

        INSERT INTO lottery_result_details (
            lottery_result_id, prize_structure_id, winning_number,
            created_at, updated_at, created_by, last_modified_by
        )
        SELECT
            v_result_id,
            ps.id,
            tr.winning_number,
            NOW(), NOW(), 'PHU123_WIN50_SEED', 'PHU123_WIN50_SEED'
        FROM tmp_phu123_results tr
        JOIN prize_structures ps
          ON ps.prize_code = tr.prize_code
         AND ps.region_id = v_region_id
         AND ps.deleted_at IS NULL
        WHERE tr.station_slot = r_res.station_slot
          AND tr.draw_offset = r_res.draw_offset;
    END LOOP;

    -- ---- tickets + serials ----
    FOR r_win IN SELECT * FROM tmp_phu123_winners ORDER BY idx
    LOOP
        v_station_id := v_stations[r_win.station_slot + 1];
        v_draw_date := CURRENT_DATE - r_win.draw_offset;

        -- Drop any leftover ticket on the same station/date/numbers (unique index).
        DELETE FROM lottery_ticket_serials s
         USING lottery_tickets t
         WHERE s.ticket_id = t.id
           AND t.station_id = v_station_id
           AND t.numbers = r_win.numbers
           AND t.draw_date = v_draw_date
           AND t.deleted_at IS NULL
           AND NOT EXISTS (
               SELECT 1 FROM order_details od
               WHERE od.lottery_ticket_serial_id = s.id
           );
        DELETE FROM lottery_tickets t
         WHERE t.station_id = v_station_id
           AND t.numbers = r_win.numbers
           AND t.draw_date = v_draw_date
           AND t.deleted_at IS NULL
           AND NOT EXISTS (
               SELECT 1 FROM lottery_ticket_serials s WHERE s.ticket_id = t.id
           );

        INSERT INTO lottery_tickets (
            station_id, numbers, draw_date, price_snapshot, status, is_active,
            batch_code, created_at, updated_at, created_by, last_modified_by
        ) VALUES (
            v_station_id, r_win.numbers, v_draw_date, 10000, 'SOLD_OUT', FALSE,
            'PN-PHU123-WIN', NOW(), NOW(), 'PHU123_WIN50_SEED', 'PHU123_WIN50_SEED'
        )
        RETURNING id INTO v_ticket_id;

        INSERT INTO lottery_ticket_serials (
            ticket_id, serial_number, status, ticket_condition, payout_state,
            input_source, station_id, draw_date, imported_by, imported_at,
            is_verified, created_at, updated_at, created_by, last_modified_by
        ) VALUES (
            v_ticket_id, r_win.serial_number, 'SOLD', 'GOOD', 'NONE',
            'MANUAL', v_station_id, v_draw_date, v_importer, NOW(),
            TRUE, NOW(), NOW(), 'PHU123_WIN50_SEED', 'PHU123_WIN50_SEED'
        );
    END LOOP;

    -- ---- orders (12) ----
    FOR r_plan IN
        SELECT * FROM (VALUES
            (1, 6, 0, 6),
            (2, 5, 6, 11),
            (3, 5, 11, 16),
            (4, 4, 16, 20),
            (5, 4, 20, 24),
            (6, 4, 24, 28),
            (7, 3, 28, 31),
            (8, 3, 31, 34),
            (9, 3, 34, 37),
            (10, 3, 37, 40),
            (11, 5, 40, 45),
            (12, 5, 45, 50)
        ) AS p(order_n, slots, cum_start, cum_end)
    LOOP
        SELECT MIN(CURRENT_DATE - w.draw_offset)
        INTO v_draw_date
        FROM tmp_phu123_winners w
        WHERE w.idx > r_plan.cum_start AND w.idx <= r_plan.cum_end;

        v_paid_at := (v_draw_date + TIME '09:45') + ((r_plan.order_n - 1) * INTERVAL '17 minutes');
        v_pickup_at := (v_draw_date + TIME '18:10') + ((r_plan.order_n - 1) * INTERVAL '9 minutes');
        v_slots := r_plan.slots;
        v_total := 10000 * v_slots;
        v_order_id := gen_random_uuid();

        INSERT INTO orders (
            id, user_id, name, phone, email, order_code, order_type, receive_type,
            total_amount, status, expected_pickup_at, actual_picked_up_at, picked_up_by,
            created_at, updated_at, created_by, last_modified_by
        ) VALUES (
            v_order_id,
            v_member,
            'Phu Nguyen',
            (SELECT phone FROM users WHERE id = v_member),
            (SELECT email FROM users WHERE id = v_member),
            'ORD-PHU123-WIN-' || LPAD(r_plan.order_n::text, 3, '0'),
            'ONLINE',
            'COUNTER_PICKUP',
            v_total,
            'COMPLETED',
            v_paid_at + INTERVAL '7 hours',
            v_pickup_at,
            v_importer,
            v_paid_at,
            NOW(),
            'PHU123_WIN50_SEED',
            'PHU123_WIN50_SEED'
        );

        INSERT INTO transactions (
            order_id, amount, gateway, status, paid_at, type, payment_ref,
            created_at, updated_at, created_by, last_modified_by
        ) VALUES (
            v_order_id,
            v_total,
            'PAYOS',
            'COMPLETED',
            v_paid_at,
            'ONLINE',
            'PAYOS-PHU123-WIN-' || LPAD(r_plan.order_n::text, 3, '0'),
            v_paid_at,
            NOW(),
            'PHU123_WIN50_SEED',
            'PHU123_WIN50_SEED'
        );

        INSERT INTO order_details (
            order_id, lottery_ticket_id, lottery_ticket_serial_id,
            quantity, price, status, handed_over_at, handed_over_by,
            created_at, updated_at, created_by, last_modified_by
        )
        SELECT
            v_order_id,
            t.id,
            s.id,
            1,
            10000,
            CASE WHEN w.online_claim THEN 'PROXY_HOLDING' ELSE 'HANDED_OVER' END,
            CASE WHEN w.online_claim THEN NULL ELSE v_pickup_at END,
            CASE WHEN w.online_claim THEN NULL ELSE v_importer END,
            v_paid_at,
            NOW(),
            'PHU123_WIN50_SEED',
            'PHU123_WIN50_SEED'
        FROM tmp_phu123_winners w
        JOIN lottery_ticket_serials s
          ON s.serial_number = w.serial_number AND s.deleted_at IS NULL
        JOIN lottery_tickets t ON t.id = s.ticket_id AND t.deleted_at IS NULL
        WHERE w.idx > r_plan.cum_start AND w.idx <= r_plan.cum_end;
    END LOOP;

    RAISE NOTICE 'PHU123 Win50 seed OK: member=%, tickets=50, online_claimable=30, orders=12',
        v_member;
END $$;

-- ---------- verification ----------
SELECT 'users' AS check, COUNT(*)::text AS value FROM users WHERE username = 'phu123'
UNION ALL
SELECT 'winning_tickets', COUNT(*)::text FROM lottery_tickets WHERE batch_code = 'PN-PHU123-WIN'
UNION ALL
SELECT 'sold_serials', COUNT(*)::text FROM lottery_ticket_serials WHERE serial_number LIKE 'PHU123W-%' AND status = 'SOLD'
UNION ALL
SELECT 'orders', COUNT(*)::text FROM orders WHERE order_code LIKE 'ORD-PHU123-WIN-%'
UNION ALL
SELECT 'online_claimable_details', COUNT(*)::text
  FROM order_details od
  JOIN orders o ON o.id = od.order_id
 WHERE o.order_code LIKE 'ORD-PHU123-WIN-%' AND od.status = 'PROXY_HOLDING'
UNION ALL
SELECT 'in_person_details', COUNT(*)::text
  FROM order_details od
  JOIN orders o ON o.id = od.order_id
 WHERE o.order_code LIKE 'ORD-PHU123-WIN-%' AND od.status = 'HANDED_OVER';

COMMIT;
