server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          # Trỏ vào thư mục config ngay tại root của dự án
          search-locations: file:./config/{application}/

  profiles:
    # Sử dụng profile "native" để đọc file từ hệ thống local
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health, info
