spring:
  datasource:
    url: ${CORE_POSTGRES_JDBC_URL:jdbc:postgresql://${CORE_POSTGRES_HOST}:${CORE_DB_PORT}/${CORE_POSTGRES_DB}?charSet=UTF-8}
    username: ${CORE_POSTGRES_USER}
    password: ${CORE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  data:
    redis:
      host: ${CORE_REDIS_HOST}
      port: ${CORE_REDIS_PORT}
      password: ${CORE_REDIS_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.daiphat: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
