spring:
  datasource:
    url: jdbc:postgresql://${CORE_POSTGRES_HOST}:${CORE_DB_PORT}/${CORE_POSTGRES_DB}?charSet=UTF-8
    username: ${CORE_POSTGRES_USER}
    password: ${CORE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  data:
    redis:
      host: ${CORE_REDIS_HOST}
      port: ${CORE_REDIS_PORT}
    mongodb:
      uri: mongodb://${CORE_MONGO_ROOT_USERNAME}:${CORE_MONGO_ROOT_PASSWORD}@${CORE_MONGO_HOST}:${CORE_MONGO_PORT}/${CORE_MONGO_DB}?authSource=admin
  mail:
    host: ${AUTH_PROD_MAIL_HOST}
    port: ${AUTH_PROD_MAIL_PORT}
    username: ${AUTH_PROD_MAIL_USERNAME}
    password: ${AUTH_PROD_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

daiphat:
  blog:
    seed:
      enabled: false
  order:
    seed:
      enabled: false

logging:
  level:
    root: INFO
    com.daiphat: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
