export enum LotteryTicketStatus {
    IN_STOCK = 'IN_STOCK',
    SOLD_OUT = 'SOLD_OUT',
    EXPIRED = 'EXPIRED',
    RESERVED = 'RESERVED',
    SOLD = 'SOLD',
    PROXY_HOLDING = 'PROXY_HOLDING',
    PENDING_RETURN = 'PENDING_RETURN',
    RETURNED = 'RETURNED',
    INTERNAL_FAULT = 'INTERNAL_FAULT',
    ISSUER_FAULT = 'ISSUER_FAULT'
}
