# Cấu hình đặc thù cho môi trường DEV (Chạy local)
smartlotto:
  gateway:
    account-service-uri: lb://ACCOUNT-SERVICE # Dùng qua Eureka để đúng chuẩn Microservices

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Các cấu hình khác (nếu có) có thể ghi cứng tại đây
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
