springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Account Service
        url: /v3/api-docs/account-service
    oauth:
      client-id: smartlotto-client
      client-secret: smartlotto-secret
      realm: smartlotto
      use-basic-authentication-with-access-code-grant: false
      use-pkce-with-authorization-code-grant: false

smartlotto:
  auth:
    keycloak:
      realm: smartlotto
      auth-server-url: http://localhost:8180
      client-id: smartlotto-client
      client-secret: smartlotto-secret
  gateway:
    account-service-uri: lb://ACCOUNT-SERVICE

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
