# Cấu hình đặc thù cho môi trường PROD (Chạy Docker/VPS)
smartlotto:
  gateway:
    account-service-uri: lb://ACCOUNT-SERVICE

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
