-- Canonical SQL seed for system_config.
--
-- Runtime defaults are also declared by SystemConfigEnum/SystemConfigSeeder.
-- This file keeps the SQL seed in one place for a clean Flyway database.
-- ON CONFLICT updates metadata only; an operator-edited config_value is preserved.

INSERT INTO system_config (
    config_key,
    config_value,
    config_type,
    data_type,
    description,
    config_name,
    unit,
    validation_rules,
    is_editable,
    is_active
)
VALUES
    ('ORDER_CANCEL_GRACE_MIN', '30', 'ORDER_SETTING', 'INT',
        'Thời gian ân hạn hủy đơn (phút)', 'Ân hạn hủy đơn', 'phút',
        '{"min":0,"max":1440}', TRUE, TRUE),
    ('CUSTOMER_CANCEL_CUTOFF', '14:30', 'ORDER_SETTING', 'TIME',
        'Giờ chốt hủy đơn của khách hàng', 'Giờ chốt hủy đơn khách hàng', 'HH:mm',
        '{"min":"00:00","max":"23:59"}', TRUE, TRUE),
    ('ORDER_PREPARE_SLA_MIN', '30', 'ORDER_SETTING', 'INT',
        'SLA chuẩn bị đơn (phút)', 'SLA chuẩn bị đơn', 'phút',
        '{"min":1,"max":1440}', TRUE, TRUE),
    ('ORDER_PAYMENT_COMPLAINT_REMINDER_ENABLED', 'true', 'ORDER_SETTING', 'BOOLEAN',
        'Bật thông báo nhắc nhân viên khi có chứng từ thanh toán của đơn đã quá thời gian thanh toán.',
        'Nhắc xử lý khiếu nại thanh toán', NULL, '{"allowedValues":["true","false"]}', TRUE, TRUE),
    ('VENDOR_RETURN_CUTOFF', '15:00', 'VENDOR_SETTING', 'TIME',
        'Giờ chốt trả vé cho đại lý (snapshot khi xác nhận bàn giao)', 'Giờ chốt trả vé đại lý', 'HH:mm',
        '{"min":"00:00","max":"23:59"}', TRUE, TRUE),
    ('VENDOR_EFFECTIVE_HANDOVER_DEADLINE_RULE', 'Tự tính theo từng phiếu', 'VENDOR_SETTING', 'STRING',
        'Hạn giao thực tế được tính theo từng phiếu: lấy mốc sớm hơn giữa giờ chốt người bán và giờ trả nhà cung cấp sớm nhất trừ thời gian đệm.',
        'Cách tính hạn giao thực tế', NULL, '{"allowEmpty":false,"maxLength":255}', FALSE, TRUE),
    ('STAFF_INCIDENT_CUTOFF', '16:00', 'REFUND_SETTING', 'TIME',
        'Giờ chốt xử lý sự cố của nhân viên', 'Giờ chốt xử lý sự cố', 'HH:mm',
        '{"min":"00:00","max":"23:59"}', TRUE, TRUE),
    ('INVALID_INFO_EXPIRED_DAYS', '7', 'REFUND_SETTING', 'INT',
        'Số ngày hết hạn thông tin không hợp lệ', 'Số ngày hết hạn thông tin không hợp lệ', 'ngày',
        '{"min":1,"max":365}', TRUE, TRUE),
    ('MAX_REFUND_REQUESTS_PER_DAY', '3', 'REFUND_SETTING', 'INT',
        'Số lượng yêu cầu hoàn tiền tối đa mỗi khách hàng được gửi trong một ngày',
        'Số yêu cầu hoàn tối đa mỗi ngày', 'lần/ngày', '{"min":1,"max":100}', TRUE, TRUE),
    ('MAX_REFUND_BANK_INFO_RETRY', '3', 'REFUND_SETTING', 'INT',
        'Số lần tối đa khách hàng được phép cập nhật thông tin tài khoản ngân hàng sau khi chuyển khoản hoàn tiền thất bại',
        'Số lần cập nhật TT ngân hàng tối đa', 'lần', '{"min":1,"max":20}', TRUE, TRUE),
    ('TICKET_AUTO_IMPORT_THRESHOLD', '50', 'TICKET_IMPORT', 'INT',
        'Số lượng vé lưu nháp tối đa trước khi hệ thống tự động lưu vào cơ sở dữ liệu.',
        'Ngưỡng số lượng vé tự động nhập', 'vé', '{"min":1,"max":10000}', TRUE, TRUE),
    ('RETURN_BUFFER_TIME', '45', 'TICKET_RETURN', 'INT',
        'Thời gian đệm (phút) trước hạn trả vé của nhà cung cấp', 'Thời gian đệm trả vé', 'phút',
        '{"min":0,"max":1440}', TRUE, TRUE),
    ('RETURN_REMINDER_TIME', '15', 'TICKET_RETURN', 'INT',
        'Thời gian (phút) trước hạn trả vé NCC để nhắc khẩn kiểm tra phiếu trả',
        'Nhắc kiểm tra trả vé', 'phút', '{"min":1,"max":1440}', TRUE, TRUE),
    ('PRIZE_PAYOUT_ONLINE_MAX_AMOUNT', '10000000', 'PAYOUT_SETTING', 'INT',
        'Giá trị giải tối đa khách được gửi yêu cầu trả thưởng online (VND)',
        'Hạn mức trả thưởng online', 'VND', '{"min":0}', TRUE, TRUE),
    ('MAX_PRIZE_PAYOUT_ONLINE_REJECT', '3', 'PAYOUT_SETTING', 'INT',
        'Số lần tối đa yêu cầu trả thưởng online bị từ chối trước khi bắt buộc đổi thưởng tại đại lý',
        'Số lần từ chối trả thưởng online tối đa', 'lần', '{"min":1,"max":20}', TRUE, TRUE),
    ('PRIZE_PAYOUT_TAX_THRESHOLD', '10000000', 'PAYOUT_SETTING', 'INT',
        'Ngưỡng miễn thuế TNCN trên giá trị giải (VND)', 'Ngưỡng thuế TNCN', 'VND',
        '{"min":0}', TRUE, TRUE),
    ('PRIZE_PAYOUT_TAX_RATE', '0.10', 'PAYOUT_SETTING', 'DECIMAL',
        'Thuế suất TNCN áp dụng phần vượt ngưỡng', 'Thuế suất TNCN', '%',
        '{"min":0,"max":1}', TRUE, TRUE),
    ('PRIZE_PAYOUT_COMMISSION_TIERS',
        '[{"upTo":10000000,"rate":0.01},{"upTo":100000000,"rate":0.007},{"upTo":1000000000,"rate":0.004},{"upTo":null,"rate":0.002}]',
        'PAYOUT_SETTING', 'JSON', 'Bậc thang hoa hồng đại lý trên giá trị giải gốc (trước thuế)',
        'Hoa hồng trả thưởng', '%', '{}', TRUE, TRUE),
    ('PRIZE_PAYOUT_COMPLAINT_PROCESSING_WAIT_HOURS', '48', 'COMPLAINT_SETTING', 'INT',
        'Số giờ tối thiểu yêu cầu trả thưởng phải ở PENDING/APPROVED trước khi khiếu nại xử lý chậm',
        'Thời gian chờ khiếu nại trả thưởng chậm', 'giờ', '{"min":1,"max":168}', TRUE, TRUE),
    ('PRIZE_PAYOUT_COMPLAINT_GRACE_DAYS', '15', 'COMPLAINT_SETTING', 'INT',
        'Số ngày khiếu nại 1-click còn hiệu lực sau COMPLETED (tính từ completed_at). Hết hạn thì ẩn nút gắn claim; khách vẫn phản ánh qua hỗ trợ chung.',
        'Thời hạn khiếu nại trả thưởng', 'ngày', '{"min":1,"max":30}', TRUE, TRUE),
    ('FORTUNE_CAST_COOLDOWN_HOURS', '1440', 'FORTUNE_SETTING', 'INT',
        'Độ dài mỗi khung giờ mở gieo quẻ theo giờ đồng hồ Việt Nam (căn từ 0h). Ví dụ 60 = mỗi giờ, 360 = mỗi 6 giờ, 1440 = mỗi ngày. Không tính từ lúc khách gieo.',
        'Khung giờ mở gieo quẻ', 'phút', '{"min":1,"max":1440}', TRUE, TRUE)
ON CONFLICT (config_key) DO UPDATE SET
    config_type = EXCLUDED.config_type,
    data_type = EXCLUDED.data_type,
    description = EXCLUDED.description,
    config_name = EXCLUDED.config_name,
    unit = EXCLUDED.unit,
    validation_rules = EXCLUDED.validation_rules,
    is_editable = EXCLUDED.is_editable,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;
