ALTER TABLE refund_requests
    ADD COLUMN IF NOT EXISTS fund_source VARCHAR(30) NOT NULL DEFAULT 'COMPANY_FUND',
    ADD COLUMN IF NOT EXISTS reimburse_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS attempt_number INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS transfer_note VARCHAR(500);

UPDATE refund_requests SET status = 'PAID' WHERE status = 'TRANSFERRED';
