export type SupplierSettlementStatus = 'OPEN' | 'RECEIPT_OVERDUE' | 'CLOSED' | 'COMPLETED';

export type SupplierSettlementReconciliationPhase =
    | 'MATCHING'
    | 'DISCREPANCY_DETECTED'
    | 'RESOLVING_IMPORT_DISCREPANCY'
    | 'RESOLVING_RETURN_DISCREPANCY'
    | 'READY_FOR_RECALCULATION'
    | 'RECALCULATED'
    | 'PAYMENT_DISCREPANCY'
    | 'COMPLETED';

export type SettlementAdjustmentReasonCode =
    | 'MISSING_IMPORT'
    | 'INSUFFICIENT_IMPORT'
    | 'WRONG_DENOMINATION'
    | 'EXCESS_IMPORT'
    | 'MISSING_RETURN'
    | 'LOST_DURING_RETURN'
    | 'EXPIRED_UNRETURNED'
    | 'EXCESS_RETURN'
    | 'SHIPPING_FEE'
    | 'LATE_PENALTY'
    | 'DISCOUNT'
    | 'OTHER';

export type SettlementAdjustmentGroupType = 'IMPORT' | 'RETURN' | 'SETTLEMENT';

export interface SupplierSettlementAdjustment {
    id: number;
    supplierSettlementId?: number | null;
    lotteryTicketSerialId?: number | null;
    groupType: SettlementAdjustmentGroupType;
    reasonCode: SettlementAdjustmentReasonCode;
    reasonLabel?: string | null;
    amount: number;
    customName?: string | null;
    autoGenerated?: boolean | null;
    note?: string | null;
    resolvedBy?: string | null;
    createdAt?: string | null;
}

export type SupplierSettlementDiscrepancyType =
    | 'IMPORT_UNIT_PRICE'
    | 'IMPORT_QUANTITY'
    | 'RETURN_QUANTITY';

export type SupplierSettlementDiscrepancyDirection = 'POSITIVE' | 'NEGATIVE';

export interface SettlementDiscrepancyItem {
    type: SupplierSettlementDiscrepancyType;
    typeLabel?: string | null;
    direction: SupplierSettlementDiscrepancyDirection;
    directionLabel?: string | null;
    difference: number;
    unit?: 'TICKET' | 'VND' | string | null;
}

export interface SupplierSettlement {
    id: number;
    lotterySupplierId: number;
    supplierName?: string | null;
    supplierCode?: string | null;
    periodFrom: string;
    periodTo: string;
    supplierSettlementCode?: string | null;
    totalImportValue: number;
    totalReturnValue: number;
    totalPaidAmount: number;
    remainingAmount: number;
    supplierSettlementReceiptUrl?: string | null;
    isReturnExpired?: boolean;
    expiredReturnValue?: number;
    status: SupplierSettlementStatus;
    statusLabel?: string | null;
    reconciliationPhase?: SupplierSettlementReconciliationPhase | null;
    reconciliationPhaseLabel?: string | null;
    systemImportQuantity?: number | null;
    systemImportValue?: number | null;
    systemReturnQuantity?: number | null;
    systemReturnValue?: number | null;
    actualTicketImportQuantity?: number | null;
    actualTicketImportValue?: number | null;
    actualReturnTicketQuantity?: number | null;
    actualReturnTicketValue?: number | null;
    originalTicketUnitPrice?: number | null;
    reconciledTicketUnitPrice?: number | null;
    /** @deprecated Temporary alias of reconciledTicketUnitPrice */
    actualTicketPrice?: number | null;
    systemTicketImportPrice?: number | null;
    actualTicketImportPrice?: number | null;
    stationCommissionSnapshots?: StationCommissionSnapshot[] | null;
    initialEstimatedSettlementValue?: number | null;
    finalSettlementValue?: number | null;
    actualPaidAmount?: number | null;
    settlementDifferenceAmount?: number | null;
    discrepancyTypes?: SupplierSettlementDiscrepancyType[] | null;
    discrepancyItems?: SettlementDiscrepancyItem[] | null;
    importQuantityMismatch?: boolean;
    importValueMismatch?: boolean;
    returnQuantityMismatch?: boolean;
    returnValueMismatch?: boolean;
    importDiscrepancyResolved?: boolean;
    returnDiscrepancyResolved?: boolean;
    unitPriceDiscrepancyResolved?: boolean;
    recalculatedTotalPaidAmount?: number | null;
    reconciliationNote?: string | null;
    paymentEvidenceUrls?: string[] | null;
    matchingConfirmedAt?: string | null;
    completedAt?: string | null;
    transactionId?: number | null;
    paidAt?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    settlementBufferMinutes?: number | null;
    paymentCutOffTime?: string | null;
    reconciliationWindowStartAt?: string | null;
    inReconciliationWindow?: boolean | null;
}

export interface SupplierSettlementKpis {
    totalImportedTickets: number;
    totalImportValue: number;
    totalSoldTickets: number;
    totalRemainingTickets: number;
    totalDamagedTickets: number;
    totalLostTickets: number;
    totalVoidedTickets: number;
    totalPreparedForReturnTickets: number;
    /** EXPIRED serials imported in this settlement period with no order_detail. */
    totalExpiredReturnTickets?: number;
    totalReturnValue: number;
    remainingPayableAmount: number;
    isReturnExpired?: boolean;
    expiredReturnValue?: number;
}

export interface SettlementStationInventory {
    lotteryStationId: number;
    lotteryStationName?: string | null;
    importedQuantity: number;
    soldQuantity: number;
    remainingQuantity: number;
    damagedQuantity: number;
    lostQuantity: number;
    voidedQuantity: number;
    returnQuantity: number;
    returnValue: number;
}

export interface SettlementStationPricing {
    lotteryStationId: number;
    lotteryStationName?: string | null;
    importedQuantity: number;
    importCost: number;
    commissionRate: number;
    netUnitPrice: number;
    actualCommissionRate?: number | null;
}

export interface StationCommissionSnapshot {
    lotteryStationId: number;
    importedQuantity?: number | null;
    systemCommissionRate?: number | null;
    actualCommissionRate?: number | null;
}

export interface SettlementOverviewImportBatch {
    id: number;
    batchCode?: string | null;
    drawDate?: string | null;
    status?: string | null;
    statusLabel?: string | null;
    totalImportedQuantity?: number | null;
    totalImportedCostValue?: number | null;
    totalDeclareQuantity?: number | null;
    totalDeclaredCostValue?: number | null;
    invoiceEvidenceUrl?: string | null;
    ticketListImageUrls?: string[] | null;
    receiptImageUrl?: string | null;
    evidenceUrl?: string | null;
}

export interface SettlementOverviewReturnBatch {
    id: number;
    batchCode?: string | null;
    drawDate?: string | null;
    status?: string | null;
    statusLabel?: string | null;
    totalQuantity?: number | null;
    totalReturnValue?: number | null;
    supplierName?: string | null;
    returnReceiptUrl?: string | null;
    returnEvidenceUrl?: string | null;
    returnCutOffTime?: string | null;
    returnCutOffAt?: string | null;
    inspectionExpired?: boolean;
    minutesUntilCutoff?: number | null;
}

export interface SupplierSettlementOverview {
    settlement: SupplierSettlement;
    kpis: SupplierSettlementKpis;
    importBatches: SettlementOverviewImportBatch[];
    returnBatches: SettlementOverviewReturnBatch[];
    inventoryByStation: SettlementStationInventory[];
    stationPricing?: SettlementStationPricing[];
    adjustments?: SupplierSettlementAdjustment[];
}

export interface SettlementResolvableSerial {
    serialId: number;
    serialNumber: string;
    status?: string | null;
    ticketCondition?: string | null;
    stationName?: string | null;
    importCost?: number | null;
    importBatchId?: number | null;
    importBatchCode?: string | null;
}

export type SettlementImportFileCheckStatus = 'PARSED' | 'NO_FILE' | 'DOWNLOAD_FAILED' | 'PARSE_FAILED';

export interface SettlementImportFileCheckFile {
    importBatchId: number;
    importBatchCode?: string | null;
    fileName?: string | null;
    originalFileUrl?: string | null;
    status: SettlementImportFileCheckStatus;
    errorMessage?: string | null;
}

export interface SettlementImportFileCheckTicket {
    serialId?: number | null;
    serialNumber: string;
    numbers?: string | null;
    lotteryStationId?: number | null;
    stationName?: string | null;
    importBatchId?: number | null;
    importBatchCode?: string | null;
    sourceFileName?: string | null;
}

export interface SettlementImportFileCheckStationSummary {
    lotteryStationId?: number | null;
    stationName?: string | null;
    fileQty: number;
    systemQty: number;
    onlyInSystemQty: number;
    onlyInFileQty: number;
}

export interface SettlementImportFileCheck {
    files: SettlementImportFileCheckFile[];
    fileTickets: SettlementImportFileCheckTicket[];
    systemTickets: SettlementImportFileCheckTicket[];
    matchedCount: number;
    onlyInSystem: SettlementImportFileCheckTicket[];
    onlyInFile: SettlementImportFileCheckTicket[];
    stationSummaries: SettlementImportFileCheckStationSummary[];
    importsTickets: boolean;
}

export interface SettlementMatchingAdditionalCost {
    additionalCost: number;
    additionalCostType: SettlementAdjustmentReasonCode;
    additionalCostReason: string;
    additionalCostCustomName?: string | null;
    autoGenerated?: boolean | null;
}

export interface ConfirmSettlementMatchingPayload {
    actualTicketImportQuantity: number;
    actualTicketImportValue: number;
    actualReturnTicketQuantity: number;
    actualReturnTicketValue: number;
    reconciledTicketUnitPrice?: number;
    reconciliationNote?: string;
    actualPaidAmount: number;
    additionalCosts?: SettlementMatchingAdditionalCost[];
    actualTicketImportPrice: number;
    stationCommissions?: Array<{ lotteryStationId: number; actualCommissionRate: number }>;
}

export interface ResolveImportDiscrepancyPayload {
    serialIds?: number[];
    ticketCondition?: 'DAMAGED' | 'LOST' | 'VOIDED' | 'UNDER_IMPORTED' | null;
    reasonCode: SettlementAdjustmentReasonCode;
    adjustmentAmount?: number | null;
    note?: string;
    markResolved: boolean;
    missingPlaceholders?: Array<{
        lotteryStationId: number | null;
        quantity: number;
        ticketCondition?: 'DAMAGED' | 'LOST' | 'VOIDED' | 'UNDER_IMPORTED';
        numbers?: string;
        serialNumber?: string;
        evidenceUrl?: string;
    }>;
    excessTickets?: Array<{ lotteryStationId: number; numbers: string; serialNumber: string }>;
    /** Required when any missing placeholder (or selected serial) is DAMAGED. */
    damagedEvidenceUrl?: string | null;
}

export interface ResolveReturnDiscrepancyPayload {
    serialIds?: number[];
    resolution?: 'EXPIRED' | 'LOST' | 'DAMAGED' | 'VOIDED';
    reasonCode: SettlementAdjustmentReasonCode;
    adjustmentAmount?: number | null;
    note?: string;
    markResolved: boolean;
    excessSerialNumbers?: string[];
}

export interface ResolveUnitPriceDiscrepancyPayload {
    note?: string;
    markResolved: boolean;
}

export interface AddSettlementMonetaryAdjustmentPayload {
    amount: number;
    reasonCode: SettlementAdjustmentReasonCode;
    note: string;
}

export interface SettlementCompleteResult {
    completed: boolean;
    settlement: SupplierSettlement;
    recalculatedTotalPaidAmount?: number | null;
    finalSettlementValue?: number | null;
    actualPaidAmount?: number | null;
    initialEstimatedSettlementValue?: number | null;
    settlementDifferenceAmount?: number | null;
    remainingDifference?: number | null;
    message?: string | null;
}

export interface SupplierSettlementListParams {
    page?: number;
    size?: number;
    lotterySupplierId?: number;
    status?: SupplierSettlementStatus;
    periodFrom?: string;
    periodTo?: string;
    search?: string;
    sortBy?: string;
    direction?: string;
}
