package com.daiphat.coreapi.adapter.in.web.controller.dashboard;
import com.daiphat.coreapi.adapter.in.web.constants.ApiConstants; import com.daiphat.coreapi.adapter.in.web.response.ApiResponse; import com.daiphat.coreapi.adapter.in.web.security.AuthenticatedUserPrincipal;
import com.daiphat.coreapi.application.dto.response.dashboard.StaffDashboardResponse; import com.daiphat.coreapi.application.port.in.dashboard.staff.*; import com.daiphat.coreapi.shared.time.VietnamClock;
import lombok.RequiredArgsConstructor; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
import java.time.LocalDate; import java.util.List;
@RestController @RequestMapping(ApiConstants.API_V1 + "/staff/dashboard") @RequiredArgsConstructor @PreAuthorize("hasAuthority('dashboard:staff')")
public class StaffDashboardController {
    private final VietnamClock clock; private final StaffTaskSummaryServicePort summary; private final StaffWorkQueueServicePort workQueue; private final StaffRecentActionServicePort recentActions; private final StaffInventoryAlertServicePort inventoryAlerts;
    @GetMapping("/task-summary") public ApiResponse<StaffDashboardResponse.TaskSummary> taskSummary(@AuthenticationPrincipal AuthenticatedUserPrincipal p, @RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate businessDate) { return ApiResponse.success(null, summary.getTaskSummary(p.getId(), day(businessDate))); }
    @GetMapping("/work-items") public ApiResponse<StaffDashboardResponse.WorkItems> workItems(@AuthenticationPrincipal AuthenticatedUserPrincipal p, @RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate businessDate, @RequestParam(required=false) String status, @RequestParam(defaultValue="1") int page, @RequestParam(defaultValue="20") int size) { return ApiResponse.success(null, workQueue.getWorkItems(p.getId(), day(businessDate), status, Math.max(page,1), Math.min(Math.max(size,1),100))); }
    @GetMapping("/recent-actions") public ApiResponse<List<StaffDashboardResponse.RecentAction>> recentActions(@AuthenticationPrincipal AuthenticatedUserPrincipal p, @RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate businessDate) { return ApiResponse.success(null, recentActions.getRecentActions(p.getId(), day(businessDate))); }
    @GetMapping("/inventory-alerts") public ApiResponse<List<StaffDashboardResponse.InventoryAlert>> inventoryAlerts(@AuthenticationPrincipal AuthenticatedUserPrincipal p, @RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate businessDate) { return ApiResponse.success(null, inventoryAlerts.getInventoryAlerts(p.getId(), day(businessDate))); }
    private LocalDate day(LocalDate value) { return value == null ? clock.today() : value; }
}
