package com.daiphat.coreapi.domain.model.enums.chat;

public enum ConversationSocketEventType {
    CONVERSATION_ESCALATED,
    CONVERSATION_ASSIGNED,
    CONVERSATION_TAKEN,
    CONVERSATION_UNASSIGNED,
    CONVERSATION_STAFF_REQUEST_CANCELLED,
    CONVERSATION_CLOSED,
    MESSAGE_READ
}
