server:
  port: 8081
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:daiphat_account_db}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/daiphat}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/daiphat/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:daiphat-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: password
            scope: openid, profile, email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/daiphat}

  # --- Cấu hình Gửi Mail (Dùng chung cho cả Dev & Prod qua Biến môi trường) ---
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# --- Cấu hình tùy chỉnh Đại Phát ---
daiphat:
  auth:
    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8180}
      realm: ${KEYCLOAK_REALM:daiphat}
      client-id: ${KEYCLOAK_CLIENT_ID:daiphat-client}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
