/**
 * Tỉnh/thành theo miền — dropdown nhà đài (tạo/sửa).
 */
export const REGION_DATA: Record<string, string[]> = {
  MIEN_BAC: [
    "Bắc Ninh",
    "Cao Bằng",
    "Điện Biên",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Phòng",
    "Hưng Yên",
    "Lào Cai",
    "Lạng Sơn",
    "Lai Châu",
    "Nghệ An",
    "Ninh Bình",
    "Phú Thọ",
    "Quảng Ninh",
    "Sơn La",
    "Thái Nguyên",
    "Thanh Hóa",
    "Tuyên Quang",
  ],
  MIEN_TRUNG: [
    "Đà Nẵng",
    "Đắk Lắk",
    "Gia Lai",
    "Khánh Hòa",
    "Quảng Ngãi",
    "Quảng Trị",
    "Huế",
  ],
  MIEN_NAM: [
    "Hồ Chí Minh",
    "TP.HCM",
    "Đồng Tháp",
    "Cà Mau",
    "Bến Tre",
    "Vũng Tàu",
    "Bạc Liêu",
    "Đồng Nai",
    "Cần Thơ",
    "Sóc Trăng",
    "Tây Ninh",
    "An Giang",
    "Bình Thuận",
    "Vĩnh Long",
    "Bình Dương",
    "Trà Vinh",
    "Long An",
    "Bình Phước",
    "Hậu Giang",
    "Tiền Giang",
    "Kiên Giang",
    "Đà Lạt (Lâm Đồng)",
  ],
};
