name: daiphat-be

services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: daiphat-postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: daiphat_core_db
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - "5433:5432"
    volumes:
      - daiphat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d daiphat_core_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - daiphat-network

  redis:
    image: redis:alpine
    container_name: daiphat-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - daiphat_redis_data:/data
    networks:
      - daiphat-network

  mongo:
    image: mongo:7
    container_name: daiphat-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: core_admin
      MONGO_INITDB_ROOT_PASSWORD: core_pass_2026
      MONGO_INITDB_DATABASE: daiphat_core_db
    ports:
      - "27018:27017"
    volumes:
      - daiphat_mongo_data:/data/db
    networks:
      - daiphat-network

networks:
  daiphat-network:
    driver: bridge

volumes:
  daiphat_postgres_data:
  daiphat_redis_data:
  daiphat_mongo_data:
