package com.daiphat.coreapi.application.dto.response.payout;

import com.daiphat.coreapi.domain.model.enums.lottery.LotteryTicketSerialStatus;
import com.daiphat.coreapi.domain.model.enums.lottery.SerialPayoutState;
import com.daiphat.coreapi.domain.model.enums.order.OrderType;
import com.daiphat.coreapi.domain.model.enums.payout.PrizePayoutChannel;
import com.daiphat.coreapi.domain.model.enums.payout.PrizePayoutOwnershipVerificationLevel;
import com.daiphat.coreapi.domain.model.enums.payout.PrizePayoutPaymentMethod;
import com.daiphat.coreapi.domain.model.enums.payout.PrizePayoutRequestStatus;
import com.daiphat.coreapi.domain.model.enums.payout.PrizePayoutTicketOrigin;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

public record PrizePayoutRequestResponse(
        Long id,
        String requestCode,
        UUID customerId,
        String customerName,
        UUID orderId,
        String orderCode,
        Long orderDetailId,
        Long serialId,
        String serialNumber,
        String numbers,
        String stationName,
        LocalDate drawDate,
        String prizeCode,
        String prizeDisplayName,
        BigDecimal grossAmount,
        BigDecimal taxAmount,
        BigDecimal commissionAmount,
        BigDecimal netAmount,
        BigDecimal cashAmount,
        BigDecimal transferAmount,
        PrizePayoutChannel channel,
        PrizePayoutTicketOrigin ticketOrigin,
        PrizePayoutOwnershipVerificationLevel ownershipVerificationLevel,
        boolean manualOwnershipConfirmed,
        OrderType orderType,
        String orderGuestName,
        String orderPhone,
        PrizePayoutPaymentMethod paymentMethod,
        Long bankAccountId,
        String bankName,
        String bankAccountNumber,
        String accountHolderName,
        String recipientFullName,
        String recipientIdNumber,
        String recipientIdImageUrl,
        String recipientIdImageBackUrl,
        LocalDateTime recipientIdentityCapturedAt,
        PrizePayoutRequestStatus status,
        int rejectCount,
        Integer maxOnlineRejectRetry,
        boolean onlineClaimLocked,
        boolean requiresFourEyes,
        boolean canCurrentStaffApprove,
        boolean canCurrentStaffComplete,
        String rejectReason,
        String transferEvidenceUrl,
        String confirmationContractUrl,
        LocalDateTime completedAt,
        String completedBy,
        String createdBy,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LotteryTicketSerialStatus serialStatus,
        SerialPayoutState payoutState
) {
}
