# Cấu hình đặc thù cho môi trường PROD (Chạy Docker/VPS)
daiphat:
  gateway:
    account-service-uri: lb://account-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      # CORS moved to Java
      routes:
        - id: account-service
          uri: ${daiphat.gateway.account-service-uri}
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/auth/**, /api/v1/users/**, /api/v1/roles/**, /api/v1/permissions/**
