server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: api-gateway

# SpringDoc Aggregation
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Account Service
        url: /v3/api-docs/account-service

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
