package com.daiphat.coreapi.application.dto.request.lotteries;

import com.daiphat.coreapi.domain.model.enums.lottery.SupplierSettlementAdjustmentReasonCode;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;

/**
 * Additional cost/adjustment entered during matching.
 * Sign convention: positive increases payable to supplier; negative decreases.
 */
public record SettlementMatchingAdjustmentItem(
        @NotNull BigDecimal additionalCost,
        @NotNull SupplierSettlementAdjustmentReasonCode additionalCostType,
        @NotBlank String additionalCostReason,
        String additionalCostCustomName,
        Boolean autoGenerated
) {
}
