package com.daiphat.coreapi.application.service.chat.schedule;

import com.daiphat.coreapi.application.config.ChatScheduleProperties;
import com.daiphat.coreapi.application.dto.chat.schedule.ChatScheduleStationMatchResult;
import com.daiphat.coreapi.application.event.LotteryStationChangedEvent;
import com.daiphat.coreapi.application.listener.ChatScheduleStationAliasIndexListener;
import com.daiphat.coreapi.application.port.out.lotteries.LotteryStationRepositoryPort;
import com.daiphat.coreapi.domain.model.enums.chat.ChatScheduleStationMatchSource;
import com.daiphat.coreapi.domain.model.enums.lottery.LotteryStationStatus;
import com.daiphat.coreapi.domain.model.lotteries.LotteryStationModel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@DisplayName("ChatScheduleStationResolver — index")
class ChatScheduleStationAliasIndexTest {

    @Mock
    private LotteryStationRepositoryPort lotteryStationRepositoryPort;

    private ChatScheduleStationResolver stationResolver;
    private ChatScheduleStationAliasIndexListener listener;

    @BeforeEach
    void setUp() {
        ChatScheduleProperties properties = new ChatScheduleProperties();
        ChatScheduleProperties.StationAlias hcm = new ChatScheduleProperties.StationAlias();
        hcm.setName("Hồ Chí Minh");
        hcm.setAliases(List.of("sai gon"));
        properties.setStations(List.of(hcm));

        stationResolver = new ChatScheduleStationResolver(properties, lotteryStationRepositoryPort);
        listener = new ChatScheduleStationAliasIndexListener(stationResolver);
    }

    @Test
    void rebuild_yamlAliasOverridesAutoGeneratedName() {
        LotteryStationModel station = new LotteryStationModel();
        station.setId(10L);
        station.setName("Hồ Chí Minh");
        station.setStatus(LotteryStationStatus.ACTIVE);
        when(lotteryStationRepositoryPort.findAll()).thenReturn(List.of(station));

        stationResolver.rebuild();

        assertThat(stationResolver.match("sai gon"))
                .isPresent()
                .get()
                .extracting(ChatScheduleStationMatchResult::source, result -> result.station().getName())
                .containsExactly(ChatScheduleStationMatchSource.YAML, "Hồ Chí Minh");
    }

    @Test
    void listener_rebuildsAfterStationChangedEvent() {
        when(lotteryStationRepositoryPort.findAll()).thenReturn(List.of());
        stationResolver.rebuild();
        assertThat(stationResolver.match("ben tre")).isEmpty();

        LotteryStationModel benTre = new LotteryStationModel();
        benTre.setId(2L);
        benTre.setName("Bến Tre");
        benTre.setStatus(LotteryStationStatus.ACTIVE);
        when(lotteryStationRepositoryPort.findAll()).thenReturn(List.of(benTre));

        listener.handleLotteryStationChanged(LotteryStationChangedEvent.builder().stationId(2L).build());

        assertThat(stationResolver.match("ben tre"))
                .isPresent()
                .get()
                .extracting(result -> result.station().getName())
                .isEqualTo("Bến Tre");
    }
}
